server:
  port: "${PORT}"
spring:
  config:
    import: optional:classpath:/env.properties
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
  datasource:
    username: "${DBUSER}"
    url: "${DBURL}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  public:
    key: classpath:/rsa.pub.pem
  private:
    key: classpath:/rsa.pem
